/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import javax.swing.JOptionPane;

/**
 *
 * @author Franz
 */
public class MainMenu extends javax.swing.JFrame {
    public static int role = 0;

    /**
     * 
     * Creates new form MainMenu2
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_input = new javax.swing.JButton();
        bt_harian = new javax.swing.JButton();
        bt_bulanan = new javax.swing.JButton();
        bt_ambil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        bt_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_daftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 249, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 430));

        bt_input.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bt_input.setForeground(new java.awt.Color(40, 38, 39));
        bt_input.setText("Input Cucian");
        bt_input.setPreferredSize(new java.awt.Dimension(95, 20));
        bt_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inputActionPerformed(evt);
            }
        });

        bt_harian.setVisible(false);
        bt_harian.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bt_harian.setForeground(new java.awt.Color(40, 38, 39));
        bt_harian.setText("Transaksi Harian");
        bt_harian.setPreferredSize(new java.awt.Dimension(95, 20));
        bt_harian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_harianActionPerformed(evt);
            }
        });

        bt_bulanan.setVisible(false);
        bt_bulanan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bt_bulanan.setForeground(new java.awt.Color(40, 38, 39));
        bt_bulanan.setText("Laporan Bulanan");
        bt_bulanan.setPreferredSize(new java.awt.Dimension(95, 20));
        bt_bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bulananActionPerformed(evt);
            }
        });

        bt_ambil.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bt_ambil.setForeground(new java.awt.Color(40, 38, 39));
        bt_ambil.setText("Ambil Cucian");
        bt_ambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ambilActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(175, 203, 255));

        lb_title.setBackground(new java.awt.Color(0, 0, 0));
        lb_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lb_title.setText("Menu");
        lb_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bt_logout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bt_logout.setForeground(new java.awt.Color(40, 38, 39));
        bt_logout.setText("Logout");
        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\GitHub_Repos\\laundry\\Resoure Design\\Menu.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_title)
                .addGap(193, 193, 193)
                .addComponent(bt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_title)
                    .addComponent(bt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bt_daftar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bt_daftar.setForeground(new java.awt.Color(40, 38, 39));
        bt_daftar.setText("Daftar Cucian");
        bt_daftar.setPreferredSize(new java.awt.Dimension(95, 20));
        bt_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_daftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_bulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_harian, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_ambil, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ambil, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_bulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_harian, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 449));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inputActionPerformed
        PilihInputCucian pilihinput = new PilihInputCucian();
        pilihinput.role = this.role;
        pilihinput.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_inputActionPerformed

    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_harianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_harianActionPerformed
        TransaksiHarian harian = new TransaksiHarian();
        harian.role = this.role;
        harian.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_harianActionPerformed

    private void bt_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_daftarActionPerformed
        DaftarCucian daftar = new DaftarCucian();
        daftar.role = this.role;
        daftar.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_daftarActionPerformed

    private void bt_bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bulananActionPerformed
        LaporanBulanan bulanan = new LaporanBulanan();
        bulanan.role = this.role;
        bulanan.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_bulananActionPerformed

    private void bt_ambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ambilActionPerformed
        // TODO add your handling code here:
        AmbilCucian cuci = new AmbilCucian();
        cuci.role = this.role;
        cuci.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_ambilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_ambil;
    public javax.swing.JButton bt_bulanan;
    public javax.swing.JButton bt_daftar;
    public javax.swing.JButton bt_harian;
    public javax.swing.JButton bt_input;
    private javax.swing.JButton bt_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
